CREATE TABLE USERS (
  EMPLOYEE_ID     NUMERIC(10) NOT NULL CHECK (EMPLOYEE_ID > 999999999),
  ROLE            INT          NOT NULL,
  EMAIL           VARCHAR(250) NOT NULL,
  HASHED_PASSWORD BINARY(60)   NOT NULL,
  LAST_LOGIN      DATETIME,
  NUMBER_FAIL     SMALLINT,
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (ROLE) REFERENCES USER_ROLES (ROLE_ID),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
);
