CREATE TABLE TIMES (
  ENTRY_ID     INT      NOT NULL IDENTITY (1,1),
  EID          NUMERIC(10) NOT NULL CHECK (EID > 999999999),
  HOURS_LOGGED FLOAT    NOT NULL,
  PROJECT_ID   INT      NOT NULL,
  ENTRY_DATE   DATETIME NOT NULL,
  PRIMARY KEY (ENTRY_ID),
  FOREIGN KEY (EID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID)
);