CREATE TABLE TEAMS (
  TEAM_ID       INT NOT NULL,
  PROJECT_ID    INT,
  DEPARTMENT_ID INT NOT NULL,
  TEAMLEAD_ID   INT NOT NULL,

  HOURS_WORKED AS (dbo.GetHoursWorked(TEAM_ID)),

  PRIMARY KEY (TEAM_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID)

);
