CREATE TABLE PROJECTS (
  PROJECT_ID             INT         NOT NULL IDENTITY (1, 1),
  NAME                   VARCHAR(70) NOT NULL,
  BUDGET                 FLOAT       NOT NULL,
  BUDGET_USED            FLOAT       NOT NULL,
  CONTROLLING_DEPARTMENT INT         NOT NULL,
  EID                    NUMERIC(10) NOT NULL CHECK (EID > 999999999),
  CHANGE_DATE            DATETIME,
  CONTROLLING_TEAM       INT,
  START_DATE             DATETIME    NOT NULL,
  STATUS_TYPE            INT         NOT NULL,

  BUDGET_USED AS dbo.GetBudgetUsed(PROJECT_ID),

  PRIMARY KEY (PROJECT_ID),
  FOREIGN KEY (EID) REFERENCES USERS (EMPLOYEE_ID),
  FOREIGN KEY (CONTROLLING_DEPARTMENT) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
  FOREIGN KEY (CONTROLLING_TEAM) REFERENCES TEAMS (TEAM_ID),
  FOREIGN KEY (STATUS_TYPE) REFERENCES STATUSES (STATUS_ID)
);



