CREATE TABLE EMPLOYEES (
  FIRST_NAME  VARCHAR(35) NOT NULL,
  MIDDLE_INIT CHAR(1),
  LAST_NAME   VARCHAR(35) NOT NULL,
  EMPLOYEE_ID NUMERIC(10) NOT NULL CHECK (EMPLOYEE_ID > 999999999),
  HOURLY_WAGE FLOAT       NOT NULL,
  MANAGES     INT,
  TEAM_ID     INT,
  NAME AS (FIRST_NAME + ' ' + MIDDLE_INIT + ' ' + LAST_NAME),
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (MANAGES) REFERENCES TEAMS (TEAM_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID)
);
