CREATE TABLE USERS (
  EMPLOYEE_ID     INT          NOT NULL,
  ROLE            INT  NOT NULL,
  EMAIL           VARCHAR(250) NOT NULL,
  HASHED_PASSWORD BINARY(60)   NOT NULL,
  LAST_LOGIN      DATETIME,
  NUMBER_FAIL     SMALLINT,
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (ROLE) REFERENCES USERS_ROLES(ROLE_ID)
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID)
);
