CREATE TABLE SESSIONS (
  ENTRY_ID     INT      NOT NULL IDENTITY (1,1),
  EID          NUMERIC(10) NOT NULL CHECK (EID > 999999999),
  SESSION_ID   VARCHAR(36)    NOT NULL,
  ROLE_ID   INT      NOT NULL,
  ENTRY_DATE   DATETIME NOT NULL,
  EXPIRATION_DATE   DATETIME NOT NULL,
  PRIMARY KEY (ENTRY_ID),
  FOREIGN KEY (EID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES USERS_ROLES (ROLE_ID)
);