CREATE TABLE USERS (
  EMPLOYEE_ID INT          NOT NULL,
  ROLE        VARCHAR(70)  NOT NULL,
  EMAIL       VARCHAR(250) NOT NULL,
  HASHED      BINARY(60)   NOT NULL,
  LAST_LOGIN  DATETIME,
  NUMBER_FAIL SMALLINT,
  TEAM_ID     INT,
  NAME        AS dbo.GetEmployeeName(EMPLOYEE_ID),
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID)
);
