CREATE TABLE TIMES (
  ENTRY_ID     INT      NOT NULL,
  EID          INT      NOT NULL,
  HOURS_LOGGED FLOAT    NOT NULL,
  PROJECT_ID   INT      NOT NULL,
  ENTRY_DATE   DATETIME NOT NULL,
  PRIMARY KEY (ENTRY_ID),
  FOREIGN KEY (EID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID)
);
