CREATE TABLE PROJECTS (
  PROJECT_ID             INT         NOT NULL,
  NAME                   VARCHAR(70) NOT NULL,
  BUDGET                 FLOAT       NOT NULL,
  BUDGET_USED            FLOAT       NOT NULL,
  CONTROLLING_DEPARTMENT INT         NOT NULL,
  EID                    NUMERIC(10) NOT NULL CHECK (EID > 999999999),
  CHANGE_DATE            DATETIME,
  COMMENT                VARCHAR(250),
  CONTROLLING_TEAM       INT,
  START_DATE             DATETIME    NOT NULL,
  STATUS_TYPE            INT         NOT NULL,
  MODIFIED       AS (EID + ' ' + CHANGE_DATE),
  CURRENT_STATUS AS (STATUS_TYPE + ' :  ' + COMMENT),

  PRIMARY KEY (PROJECT_ID),
  FOREIGN KEY (EID) REFERENCES USERS (EMPLOYEE_ID),
  FOREIGN KEY (CONTROLLING_DEPARTMENT) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
  FOREIGN KEY (CONTROLLING_TEAM) REFERENCES TEAMS (TEAM_ID),
  FOREIGN KEY (STATUS_TYPE) REFERENCES STATUSES (STATUS_ID)
);

DROP TABLE PROJECTS;
