CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID       INT          NOT NULL IDENTITY (1, 1) PRIMARY KEY,
  NAME     VARCHAR(70)  NOT NULL,
  STREET_NUMBER VARCHAR(20) NOT NULL,
  STREET_NAME VARCHAR(50) NOT NULL,
  CITY VARCHAR(60) NOT NULL,
  STATE_PROVINCE_REGION VARCHAR(50) NOT NULL,
  ZIPCODE VARCHAR(16) NOT NULL,
  COUNTRY VARCHAR(90) NOT NULL,
  UNIQUE (NAME),
  NUMBER_OF_EMPLOYEES              AS (dbo.GetNumberOfEmployees(ID))
);